### ISSUE TITLE
Joint CAD

### ISSUE THREAD

**Issue by louisprimeau** [lolzballs/esc204#1]
We need to do joint CAD, and detailed design decisions on the composition of those joints, i.e. 3D printed parts, bearings, etc.

- [x] CAD
- [x] 3D Printing

**Comment by JonEsparaz** [comment]
@louisprimeau we need to modify the end-most joint's CAD to integrate the ToF sensors and camera.

**Comment by JonEsparaz** [comment]
I’m going to close this issue in favour of opening a new one for CAD that can accommodate our sensors.
