### ISSUE TITLE
Create nice wrappers for servos and steppers

### ISSUE THREAD

**Issue by lolzballs** [lolzballs/esc204#19]
We want to be able to give high level commands to control the servos and steppers.

I'm thinking about having our high level logic in python, and the low-level drivers in individual C programs which can have commands sent to them through `stdio`.

**Comment by JonEsparaz** [comment]
@lolzballs will `kinematics.py` interface with `commands.c`?

**Comment by lolzballs** [comment]
Wrappers are done, so all that's left is the actual motion code.
